#!/usr/bin/env python3
# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier:  MIT

"""Build the dnn-benchmark release wheels.

Produces, into ``--output``:

* ``hipdnn_runtime_<arch>``  -- one platform wheel per GPU architecture, holding
  ``libhipdnn_backend.so`` and the engine plugins compiled for that target.
* ``hipdnn_frontend``        -- the nanobind bindings. Host code only, so one
  ``cp312-abi3`` wheel covers every architecture and every Python >= 3.12.
* ``dnn_benchmarking``       -- the pure-Python benchmark package.

Together these replace the from-source ``setup_env.py`` path for users: they
install with pip and never need a compiler, CMake, or ``rocm-sdk-devel``.

Run with the *system* interpreter; the script owns a build venv holding the
ROCm SDK (``--build-venv``, created on first use)::

    python3 tools/build_release_wheels.py --arch gfx90a

Stdlib only, and deliberately so: this runs before the build venv exists.
"""

import argparse
import hashlib
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import urllib.parse
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROCM_LIBRARIES_DIR = REPO_ROOT / "rocm-libraries"
ROCM_LIBRARIES_URL = "https://github.com/ROCm/rocm-libraries.git"
HIPDNN_ROOT = ROCM_LIBRARIES_DIR / "projects" / "hipdnn"
RUNTIME_TEMPLATE_DIR = Path(__file__).resolve().parent / "release" / "hipdnn_runtime"

ROCM_TORCH_INDEX_URL = "https://rocm.nightlies.amd.com/whl-multi-arch/"

DEFAULT_ARCHS = ("gfx90a", "gfx942", "gfx950", "gfx1100", "gfx1151")

# Pinned because the superbuild's CMakePresets.json needs presets v6 (CMake
# >= 3.25) while CMake 4 drops the <3.5 compatibility the ROCm dependency tree
# still relies on.
CMAKE_PIN = "cmake==3.31.6"

# The interpreter floor, mirroring requires-python in pyproject.toml.
PYTHON_FLOOR = "3.12"

# Loader search paths baked into the packaged payload, relative to each file.
# They reach the sibling ROCm SDK wheels in the same site-packages, which is
# what lets a pip install work with no LD_LIBRARY_PATH and no activation script.
RUNTIME_RPATHS = {
    # <site-packages>/hipdnn_runtime/lib/*.so
    "lib": "$ORIGIN:$ORIGIN/../../_rocm_sdk_core/lib:$ORIGIN/../../_rocm_sdk_libraries/lib",
    # <site-packages>/hipdnn_runtime/lib/hipdnn_plugins/engines/*.so
    "engines": (
        "$ORIGIN/../..:$ORIGIN/../../../../_rocm_sdk_core/lib"
        ":$ORIGIN/../../../../_rocm_sdk_libraries/lib"
    ),
}
# <site-packages>/hipdnn_frontend/*.so needs the backend from the runtime wheel.
FRONTEND_RPATH = (
    "$ORIGIN:$ORIGIN/../hipdnn_runtime/lib"
    ":$ORIGIN/../_rocm_sdk_core/lib:$ORIGIN/../_rocm_sdk_libraries/lib"
)

SETUP_PY_TEMPLATE = '''\
# Generated by tools/build_release_wheels.py. Do not edit.
"""Packs a prebuilt hipDNN payload for one GPU architecture into a wheel."""

import os

from setuptools import Distribution, setup


class BinaryDistribution(Distribution):
    """Force a platform wheel: the payload is compiled device and host code."""

    def has_ext_modules(self):
        return True


def payload_files():
    """Every packaged file, relative to the package directory.

    Listed explicitly rather than by glob so a missing install artifact shows up
    as an absent file in the wheel instead of a silently empty pattern.
    """
    root = os.path.join("src", "hipdnn_runtime")
    found = []
    for dirpath, _dirnames, filenames in os.walk(os.path.join(root, "lib")):
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            found.append(os.path.relpath(path, root))
    if not found:
        raise RuntimeError("no payload staged under hipdnn_runtime/lib")
    return sorted(found)


setup(
    distclass=BinaryDistribution,
    package_dir={{"": "src"}},
    packages=["hipdnn_runtime"],
    package_data={{"hipdnn_runtime": payload_files()}},
    include_package_data=False,
    zip_safe=False,
    options={{
        "bdist_wheel": {{
            "plat_name": "{plat_name}",
            # Nothing here touches the CPython API, so the wheel is valid for
            # every interpreter the rest of the stack supports.
            "py_limited_api": "cp312",
        }},
    }},
)
'''

PYPROJECT_TEMPLATE = """\
# Generated by tools/build_release_wheels.py. Do not edit.
[build-system]
requires = ["setuptools>=70.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hipdnn-runtime-{arch}"
version = "{version}"
requires-python = ">=3.12"
description = "Prebuilt hipDNN backend and engine plugins for {arch}"
license = "MIT"

[[project.authors]]
name = "Advanced Micro Devices, Inc."
"""


def fail(*lines):
    for line in lines:
        print(line, file=sys.stderr)
    sys.exit(1)


def run(cmd, **kwargs):
    print(f"+ {' '.join(str(part) for part in cmd)}", flush=True)
    return subprocess.run([str(part) for part in cmd], check=True, **kwargs)


def git_output(*args, cwd: Path) -> str:
    return subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, check=True
    ).stdout.strip()


def ensure_pinned_rocm_libraries() -> str:
    """Check out the rocm-libraries commit this repository pins; return its SHA.

    Release wheels must match the submodule pin, not whatever branch tip a
    checkout happens to track. Without a checkout, fetch only the pinned commit
    as a sparse, blobless clone of the hipDNN and provider sources instead of
    the full monorepo.
    """
    pinned = git_output("rev-parse", "HEAD:rocm-libraries", cwd=REPO_ROOT)
    if not (ROCM_LIBRARIES_DIR / ".git").exists():
        if ROCM_LIBRARIES_DIR.exists():
            shutil.rmtree(ROCM_LIBRARIES_DIR)
        run(
            [
                "git",
                "clone",
                "--quiet",
                "--filter=blob:none",
                "--sparse",
                "--no-checkout",
                ROCM_LIBRARIES_URL,
                ROCM_LIBRARIES_DIR,
            ]
        )
        # `init --cone` first: git before 2.35 has no `set --cone`, and before
        # 2.37 `set` alone writes non-cone patterns that leave out the root
        # CMakeLists.txt and CMakePresets.json.
        run(["git", "-C", ROCM_LIBRARIES_DIR, "sparse-checkout", "init", "--cone"])
        run(
            [
                "git",
                "-C",
                ROCM_LIBRARIES_DIR,
                "sparse-checkout",
                "set",
                "cmake",
                "projects/hipdnn",
                "dnn-providers",
            ]
        )
    have_pin = subprocess.run(
        ["git", "-C", ROCM_LIBRARIES_DIR, "cat-file", "-e", f"{pinned}^{{commit}}"],
        capture_output=True,
    )
    if have_pin.returncode != 0:
        run(
            [
                "git",
                "-C",
                ROCM_LIBRARIES_DIR,
                "fetch",
                "--quiet",
                "--depth",
                "1",
                "origin",
                pinned,
            ]
        )
    # Check out even when HEAD already names the pin: a --no-checkout clone
    # whose default-branch tip is the pin has HEAD there and no files at all.
    run(["git", "-C", ROCM_LIBRARIES_DIR, "checkout", "--quiet", pinned])
    return pinned


# --- build venv ------------------------------------------------------------


class BuildEnv:
    """The venv holding the ROCm toolchain every arch build compiles against.

    One venv serves every architecture: compiling for a target needs only the
    devel SDK's clang plus ``GPU_TARGETS``, not that target's device wheel.
    """

    def __init__(self, venv_dir: Path, index_url: str) -> None:
        self.dir = venv_dir
        self.index_url = index_url

    @property
    def python(self) -> Path:
        return self.dir / "bin" / "python"

    @property
    def bin(self) -> Path:
        return self.dir / "bin"

    def site_packages(self) -> Path:
        result = subprocess.run(
            [
                str(self.python),
                "-c",
                "import sysconfig; print(sysconfig.get_path('purelib'))",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        return Path(result.stdout.strip())

    def distribution_version(self, name: str) -> str:
        """Version of a distribution installed in the build venv."""
        result = subprocess.run(
            [
                str(self.python),
                "-c",
                f"from importlib.metadata import version; print(version({name!r}))",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()

    def nightly_torch_version(self) -> str:
        """Newest final torch release the index built against this ROCm SDK.

        The requirements file pins torch to it. PyPI is an extra index there,
        and pip gives indexes no priority, so an unpinned torch can resolve to
        a newer PyPI build that has no ROCm device extra. PyPI never carries a
        ``+rocm`` local version, so the exact pin matches only the nightly.

        Each ROCm nightly is built for several torch versions, including an
        alpha from torch's main branch. Prefer the newest final release: on
        the 10.1.0a20260822 nightly, 2.15.0a0 fails every kernel launch on
        gfx90a with "device kernel image is invalid", while 2.14.0 runs.
        """
        rocm_version = self.distribution_version("rocm")
        url = f"{self.index_url.rstrip('/')}/torch/"
        with urllib.request.urlopen(url) as response:
            page = urllib.parse.unquote(response.read().decode("utf-8"))
        local = re.escape(f"+rocm{rocm_version}")
        found = sorted(set(re.findall(rf"torch-([\w.]+{local})-", page)))
        if not found:
            fail(f"ERROR: {url} lists no torch built against ROCm {rocm_version}.")
        # PEP 440 ordering needs `packaging`, which the build venv has (`build`
        # depends on it) and the system interpreter running this may not.
        result = subprocess.run(
            [
                str(self.python),
                "-c",
                "import sys; from packaging.version import Version; "
                "found = [Version(v) for v in sys.argv[1:]]; "
                "final = [v for v in found if not v.is_prerelease]; "
                "print(max(final or found))",
                *found,
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()

    def pip(self, *args) -> None:
        run([self.python, "-m", "pip", "install", *args])

    def uninstall(self, *names: str) -> None:
        run([self.python, "-m", "pip", "uninstall", "--quiet", "--yes", *names])

    def ensure(self) -> None:
        if self.python.is_file():
            print(f"Reusing build venv at {self.dir}")
            return
        print(f"Creating build venv at {self.dir}")
        run([sys.executable, "-m", "venv", str(self.dir)])
        self.pip("--quiet", "--upgrade", "pip")
        # rocm-sdk-devel carries clang and the HIP CMake config; rocm-sdk-libraries
        # carries MIOpen/hipBLASLt to link against. Neither is architecture
        # specific, so no device package is needed here.
        self.pip(
            "--pre",
            "rocm[libraries,devel]",
            "--index-url",
            self.index_url,
        )
        self.pip("--quiet", CMAKE_PIN, "ninja", "build")

    def devel_prefix(self) -> Path:
        """Expand and locate the rocm-sdk-devel payload."""
        result = subprocess.run(
            [str(self.python), "-m", "rocm_sdk", "path", "--root"],
            capture_output=True,
            text=True,
            check=True,
        )
        lines = [line for line in result.stdout.splitlines() if line.strip()]
        if not lines:
            fail(
                "ERROR: `rocm-sdk path --root` printed nothing; rocm-sdk-devel is broken."
            )
        return Path(lines[-1].strip())

    def build_env(self) -> dict:
        """Child environment for CMake: venv tools first, no inherited ROCM_PATH."""
        env = dict(os.environ)
        env["PATH"] = f"{self.bin}{os.pathsep}{env.get('PATH', '')}"
        env.pop("ROCM_PATH", None)
        return env


# --- native build ----------------------------------------------------------


def superbuild(env: BuildEnv, arch: str, build_dir: Path, stage_dir: Path) -> None:
    """Compile hipDNN and the engine plugins for one architecture."""
    site_packages = env.site_packages()
    devel = env.devel_prefix()
    libraries = site_packages / "_rocm_sdk_libraries"
    core = site_packages / "_rocm_sdk_core"

    for path in (build_dir, stage_dir):
        if path.exists():
            shutil.rmtree(path)
    stage_dir.mkdir(parents=True)

    cmake = env.bin / "cmake"
    run(
        [
            cmake,
            "--preset",
            "hipdnn-providers-all",
            "-GNinja",
            "-B",
            build_dir,
            f"-DROCM_PATH={devel}",
            f"-DCMAKE_PREFIX_PATH={stage_dir};{libraries};{core};{devel}",
            f"-DCMAKE_PROGRAM_PATH={devel}/bin;{devel}/lib/llvm/bin",
            f"-DCMAKE_INSTALL_PREFIX={stage_dir}",
            "-DROCM_LIBS_ENABLE_COMPONENTS=hipdnn;miopen-provider;"
            "hipblaslt-provider;hip-kernel-provider",
            f"-DGPU_TARGETS={arch}",
            f"-DAMDGPU_TARGETS={arch}",
            "-DHIPDNN_SKIP_TESTS=ON",
            "-DHIPDNN_ENABLE_SDPA=ON",
            "-DMIOPENPROVIDER_SKIP_TESTS=ON",
            "-DHIPKERNELPROVIDER_ENABLE_TESTS=OFF",
            "-DENABLE_ASM_SDPA_ENGINE=ON",
            "-DENABLE_CLANG_FORMAT=OFF",
            "-DENABLE_CLANG_TIDY=OFF",
        ],
        cwd=ROCM_LIBRARIES_DIR,
        env=env.build_env(),
    )
    run([cmake, "--build", build_dir], env=env.build_env())
    run([cmake, "--install", build_dir], env=env.build_env())


def set_rpath(path: Path, rpath: str) -> None:
    run(["patchelf", "--set-rpath", rpath, str(path)])


# --- wheel staging ---------------------------------------------------------


def stage_runtime_payload(
    stage_dir: Path, arch: str, commit: str, package_dir: Path
) -> None:
    """Copy the installed payload into an importable hipdnn_runtime package.

    Only the runtime artifacts are taken: headers, CMake config, and the
    ``hipdnn_list_engines`` tool are build-time or developer surface that a
    benchmark run never touches.
    """
    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir(parents=True)

    init_source = (RUNTIME_TEMPLATE_DIR / "__init__.py").read_text(encoding="utf-8")
    (package_dir / "__init__.py").write_text(
        init_source.replace("@GPU_ARCH@", arch).replace(
            "@ROCM_LIBRARIES_COMMIT@", commit
        ),
        encoding="utf-8",
    )

    lib_dir = package_dir / "lib"
    lib_dir.mkdir()
    backend = stage_dir / "lib" / "libhipdnn_backend.so"
    if not backend.is_file():
        fail(f"ERROR: superbuild produced no {backend}")
    shutil.copy2(backend, lib_dir / backend.name)

    engines_source = stage_dir / "lib" / "hipdnn_plugins" / "engines"
    if not engines_source.is_dir():
        fail(f"ERROR: superbuild produced no engine plugins at {engines_source}")
    engines_dir = lib_dir / "hipdnn_plugins" / "engines"
    shutil.copytree(engines_source, engines_dir)

    prune_foreign_asm_kernels(engines_dir, arch)

    set_rpath(lib_dir / backend.name, RUNTIME_RPATHS["lib"])
    for plugin in sorted(engines_dir.glob("*.so")):
        set_rpath(plugin, RUNTIME_RPATHS["engines"])


def prune_foreign_asm_kernels(engines_dir: Path, arch: str) -> int:
    """Drop the prebuilt assembly SDPA kernels for other architectures.

    ``ENABLE_ASM_SDPA_ENGINE`` installs every architecture's ``.co`` blobs
    regardless of ``GPU_TARGETS``; in a per-arch wheel the rest are dead weight
    (about 10 MB on a 23 MB install). Returns the number of directories removed.
    """
    asm_root = engines_dir / "hip_kernel_provider" / "asm_kernels"
    if not asm_root.is_dir():
        return 0
    removed = 0
    for candidate in sorted(asm_root.iterdir()):
        if candidate.is_dir() and candidate.name != arch:
            shutil.rmtree(candidate)
            removed += 1
    return removed


def build_runtime_wheel(
    env: BuildEnv,
    stage_dir: Path,
    arch: str,
    commit: str,
    version: str,
    output_dir: Path,
) -> Path:
    plat_name = f"linux_{platform.machine()}"
    with tempfile.TemporaryDirectory() as temp_name:
        build_root = Path(temp_name) / "wheel-src"
        stage_runtime_payload(
            stage_dir, arch, commit, build_root / "src" / "hipdnn_runtime"
        )
        (build_root / "pyproject.toml").write_text(
            PYPROJECT_TEMPLATE.format(arch=arch, version=version), encoding="utf-8"
        )
        (build_root / "setup.py").write_text(
            SETUP_PY_TEMPLATE.format(plat_name=plat_name), encoding="utf-8"
        )
        wheelhouse = Path(temp_name) / "wheelhouse"
        run([env.python, "-m", "build", "--wheel", "--outdir", wheelhouse, build_root])
        return collect_one(wheelhouse, f"hipdnn_runtime_{arch}-*.whl", output_dir)


def build_frontend_wheel(env: BuildEnv, stage_dir: Path, output_dir: Path) -> Path:
    """Build the nanobind bindings once; they hold no device code."""
    build_dir = stage_dir.parent / "frontend_bindings"
    if build_dir.exists():
        shutil.rmtree(build_dir)

    site_packages = env.site_packages()
    devel = env.devel_prefix()
    cmake = env.bin / "cmake"
    run(
        [
            cmake,
            "-S",
            HIPDNN_ROOT / "python" / "frontend_bindings",
            "-B",
            build_dir,
            "-GNinja",
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DCMAKE_TOOLCHAIN_FILE={ROCM_LIBRARIES_DIR / 'cmake/toolchains/rocm-clang.cmake'}",
            f"-DROCM_PATH={devel}",
            f"-DCMAKE_PREFIX_PATH={stage_dir};{site_packages / '_rocm_sdk_libraries'}"
            f";{site_packages / '_rocm_sdk_core'};{devel}",
            f"-DCMAKE_PROGRAM_PATH={devel}/bin;{devel}/lib/llvm/bin",
            f"-DPython_EXECUTABLE={env.python}",
        ],
        env=env.build_env(),
    )
    run([cmake, "--build", build_dir], env=env.build_env())

    # Repoint the extension at the runtime wheel before packing: the upstream
    # build assumes hipDNN sits on LD_LIBRARY_PATH, which is exactly the
    # assumption a pip install has to drop.
    extensions = sorted(build_dir.rglob("hipdnn_frontend_python*.so"))
    if len(extensions) != 1:
        fail(
            f"ERROR: expected exactly one built frontend extension, found {extensions}"
        )
    set_rpath(extensions[0], FRONTEND_RPATH)

    with tempfile.TemporaryDirectory() as temp_name:
        wheelhouse = Path(temp_name)
        run(
            [
                env.python,
                HIPDNN_ROOT
                / "python"
                / "frontend_wheel_package"
                / "pack_frontend_wheel.py",
                "--build-dir",
                build_dir,
                "--wheel-dir",
                wheelhouse,
            ]
        )
        return collect_one(wheelhouse, "hipdnn_frontend-*.whl", output_dir)


def build_benchmark_wheel(env: BuildEnv, output_dir: Path) -> Path:
    with tempfile.TemporaryDirectory() as temp_name:
        wheelhouse = Path(temp_name)
        run([env.python, "-m", "build", "--wheel", "--outdir", wheelhouse, REPO_ROOT])
        return collect_one(wheelhouse, "dnn_benchmarking-*.whl", output_dir)


# Runs in a fresh interpreter for each architecture: the backend SONAME can be
# loaded only once per process. argv: <arch> <1 if the install tree had ASM
# SDPA kernels for arch, else 0>.
PAYLOAD_CHECK = """\
import importlib.util, os, subprocess, sys
from pathlib import Path

arch, expect_asm = sys.argv[1], sys.argv[2] == "1"
import hipdnn_runtime

assert hipdnn_runtime.__gpu_arch__ == arch, hipdnn_runtime.__gpu_arch__
plugins = sorted(hipdnn_runtime.plugin_path().glob("*.so"))
assert plugins, "no engine plugins packaged"


def unresolved(library, symbols=True):
    # `ldd -r` resolves one file's DT_NEEDED through its own RPATH, the way a
    # process that has preloaded nothing would. In-process loads cannot show
    # this: the runtime preload puts every SONAME in place first.
    out = subprocess.run(["ldd", "-r", str(library)], capture_output=True, text=True)
    return [
        line.strip()
        for line in (out.stdout + out.stderr).splitlines()
        if "not found" in line or (symbols and "undefined symbol" in line)
    ]


frontend = Path(importlib.util.find_spec("hipdnn_frontend").origin).parent
# The bindings leave the Python C API undefined for the interpreter to supply,
# so only missing libraries count against them.
checks = [(hipdnn_runtime.backend_library(), True)]
checks += [(plugin, True) for plugin in plugins]
checks += [(module, False) for module in frontend.glob("*.so")]
for library, symbols in checks:
    problems = unresolved(library, symbols)
    assert not problems, f"{library}: " + "; ".join(problems[:5])

from dnn_benchmarking.common.rocm_runtime import initialize_pip_rocm_runtime

assert initialize_pip_rocm_runtime(), "the pip ROCm runtime did not initialize"
# Extension modules load with RTLD_NOW, so this fails on any backend entry
# point the bindings need and the preloaded backend lacks.
import hipdnn_frontend  # noqa: F401
import rocm_sdk

# What ROCm torch's _rocm_init does on `import torch`. It preloads "hipdnn" by
# absolute path, which maps the SDK's copy beside ours unless rocm_runtime has
# claimed that shortname; two backends in one process segfault in autotune.
rocm_sdk.initialize_process(preload_shortnames=["hipdnn"])
with open("/proc/self/maps", encoding="utf-8") as maps:
    backends = {l.split()[-1] for l in maps if "libhipdnn_backend" in l}
assert backends == {str(hipdnn_runtime.backend_library())}, backends

asm = hipdnn_runtime.plugin_path() / "hip_kernel_provider" / "asm_kernels"
assert os.environ["HIPDNN_AITER_ASM_DIR"] == str(asm)
shipped = sorted(p.name for p in asm.iterdir()) if asm.is_dir() else []
assert shipped == ([arch] if expect_asm else []), shipped
assert not expect_asm or any(asm.rglob("*.co")), "ASM kernel directory is empty"
print(f"{arch}: backend, bindings, and {len(plugins)} plugins resolve;"
      f" ASM kernels: {shipped or 'none'}")
"""


def check_wheels(
    env: BuildEnv,
    runtime_wheels: dict[str, Path],
    frontend: Path,
    benchmark: Path,
    work_dir: Path,
) -> None:
    """Load every architecture's payload against the pinned ROCm SDK.

    Needs no GPU. It proves that each packaged library and plugin resolves its
    dependencies and symbols through the packaged RPATHs, that the bindings use
    the wheel's backend, and that each wheel carries its own architecture's ASM
    kernels and no others. The build venv already holds the SDK version that
    the requirements file pins, so it stands in for a user venv without a
    second multi-GB download. The wheels are uninstalled again afterwards.
    """
    check_script = work_dir / "check_payload.py"
    check_script.write_text(PAYLOAD_CHECK, encoding="utf-8")
    child_env = {
        key: value
        for key, value in os.environ.items()
        if key not in ("ROCM_PATH", "LD_LIBRARY_PATH", "HIPDNN_AITER_ASM_DIR")
    }
    installed = ["hipdnn-frontend", "dnn-benchmarking"]
    env.pip("--quiet", frontend, benchmark)
    try:
        run([env.bin / "dnn-benchmark", "--help"], stdout=subprocess.DEVNULL)
        for arch, wheel in runtime_wheels.items():
            installed.append(f"hipdnn-runtime-{arch}")
            env.pip("--quiet", "--no-deps", wheel)
            asm = (
                work_dir
                / "stage"
                / arch
                / "lib"
                / "hipdnn_plugins"
                / "engines"
                / "hip_kernel_provider"
                / "asm_kernels"
                / arch
            )
            expect_asm = "1" if asm.is_dir() else "0"
            run(
                [env.python, check_script, arch, expect_asm],
                env=child_env,
                cwd=work_dir,
            )
            env.uninstall(installed.pop())
    finally:
        env.uninstall(*installed)


def collect_one(wheelhouse: Path, pattern: str, output_dir: Path) -> Path:
    wheels = sorted(wheelhouse.glob(pattern))
    if len(wheels) != 1:
        fail(f"ERROR: expected exactly one {pattern} in {wheelhouse}, found {wheels}")
    output_dir.mkdir(parents=True, exist_ok=True)
    destination = output_dir / wheels[0].name
    shutil.copy2(wheels[0], destination)
    return destination


def write_requirements(
    env: BuildEnv,
    arch: str,
    wheels: dict[str, Path],
    commit: str,
    torch_version: str,
    base_url: str,
    output_dir: Path,
) -> Path:
    """Emit a requirements file that installs everything in one pip command.

    pip cannot pin one requirement to one index, but it honours index options
    inside a requirements file -- and accepts that file over https. So the index
    wiring ships with the release instead of landing in the user's shell.

    The wheels built here are named by direct URL with a sha256 fragment. None
    of their names is registered on PyPI, which this file adds as an extra
    index for numpy and psutil; a name-only requirement would let anyone who
    registers one of those names there take over the install. A direct URL is
    the only candidate pip considers, and pip rejects a download whose hash
    differs. It also makes pip read Requires-Python from the wheel metadata,
    so a too-old interpreter fails with a message that names the floor.

    torch and the ROCm SDK are pinned exactly, to the nightly these wheels were
    compiled and verified against. hipDNN and the SDK share library names, so a
    skewed pair fails at load time, not at install time.
    """
    rocm_version = env.distribution_version("rocm")
    path = output_dir / f"requirements-{arch}.txt"
    direct = "\n".join(
        f"{name} @ {base_url}/{wheel.name}"
        f"#sha256={hashlib.sha256(wheel.read_bytes()).hexdigest()}"
        for name, wheel in wheels.items()
    )
    path.write_text(
        textwrap.dedent(
            f"""\
            # dnn-benchmarking for {arch}, against ROCm {rocm_version} and
            # rocm-libraries {commit}. Needs Python >= {PYTHON_FLOOR}.
            # Install with:
            #   pip install -r {path.name}
            --index-url {env.index_url}
            --extra-index-url https://pypi.org/simple
            --pre
            torch[device-{arch}]=={torch_version}
            rocm[libraries,device-{arch}]=={rocm_version}
            """
        )
        + direct
        + "\n",
        encoding="utf-8",
    )
    return path


# --- CLI -------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--arch",
        action="append",
        dest="archs",
        metavar="GFXNNN",
        help=(
            "GPU architecture to build a runtime wheel for. Repeatable. "
            f"Default: {' '.join(DEFAULT_ARCHS)}"
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "dist",
        help="Directory to write the wheels to. Default: %(default)s",
    )
    parser.add_argument(
        "--base-url",
        default="",
        help=(
            "URL the wheels will be downloaded from, e.g. a GitHub Release "
            "download URL. The generated requirements files name each wheel "
            "under it. Defaults to --output, which works for a local install."
        ),
    )
    parser.add_argument(
        "--build-venv",
        type=Path,
        default=REPO_ROOT / ".relbuild" / "venv",
        help="Venv holding the ROCm build toolchain. Default: %(default)s",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=REPO_ROOT / ".relbuild",
        help="Scratch directory for CMake build and install trees. Default: %(default)s",
    )
    parser.add_argument(
        "--index-url",
        default=ROCM_TORCH_INDEX_URL,
        help="Index the ROCm SDK build dependencies come from. Default: %(default)s",
    )
    parser.add_argument(
        "--version",
        default="",
        help=(
            "Version for the hipdnn-runtime wheels. Defaults to the "
            "dnn-benchmarking version in pyproject.toml."
        ),
    )
    parser.add_argument(
        "--skip-native",
        action="store_true",
        help="Reuse the install trees already under --work-dir instead of recompiling.",
    )
    return parser


def benchmark_version() -> str:
    """Read the version out of pyproject.toml without a TOML dependency."""
    for line in (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8").splitlines():
        if line.startswith("version ="):
            return line.split("=", 1)[1].strip().strip('"')
    fail("ERROR: no version found in pyproject.toml")


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    archs = args.archs or list(DEFAULT_ARCHS)
    version = args.version or benchmark_version()

    if platform.system() != "Linux":
        fail("ERROR: release wheels are built on Linux only.")
    if not shutil.which("patchelf"):
        fail("ERROR: patchelf not found on PATH; it rewrites the packaged RPATHs.")
    commit = ensure_pinned_rocm_libraries()
    if not (ROCM_LIBRARIES_DIR / "CMakePresets.json").is_file():
        fail(
            f"ERROR: {ROCM_LIBRARIES_DIR} is populated but has no CMakePresets.json.",
            "Check out a rocm-libraries ref that contains the superbuild presets.",
        )

    env = BuildEnv(args.build_venv.resolve(), args.index_url)
    env.ensure()

    output_dir = args.output.resolve()
    work_dir = args.work_dir.resolve()
    runtime_wheels = {}

    for arch in archs:
        stage_dir = work_dir / "stage" / arch
        if not args.skip_native:
            superbuild(env, arch, work_dir / "build" / arch, stage_dir)
        elif not stage_dir.is_dir():
            fail(f"ERROR: --skip-native was passed but {stage_dir} does not exist.")
        runtime_wheels[arch] = build_runtime_wheel(
            env, stage_dir, arch, commit, version, output_dir
        )

    # Arch-independent, so any populated install tree can supply the headers
    # and the backend to link against.
    frontend = build_frontend_wheel(env, work_dir / "stage" / archs[0], output_dir)
    benchmark = build_benchmark_wheel(env, output_dir)
    built = [*runtime_wheels.values(), frontend, benchmark]
    check_wheels(env, runtime_wheels, frontend, benchmark, work_dir)

    base_url = (args.base_url or output_dir.as_uri()).rstrip("/")
    torch_version = env.nightly_torch_version()
    requirements = [
        write_requirements(
            env,
            arch,
            {
                f"hipdnn-runtime-{arch}": wheel,
                "hipdnn-frontend": frontend,
                "dnn-benchmarking": benchmark,
            },
            commit,
            torch_version,
            base_url,
            output_dir,
        )
        for arch, wheel in runtime_wheels.items()
    ]

    print()
    print(f"Wheels written to {output_dir}:")
    for wheel in built:
        print(f"  {wheel.name}  ({wheel.stat().st_size / 1e6:.1f} MB)")
    for path in requirements:
        print(f"  {path.name}")
    print()
    print(
        textwrap.dedent(
            f"""\
            Install on a {archs[0]} host with:

              pip install -r {requirements[0]}
            """
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
